---
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
baseurl: "/draw_uml"
docsurl: '/draw_uml/docs'
encoding: UTF-8
exclude:
- README.md
- tmp
name: DrawUML
copyright: 2014, ogom
swatchtheme: cosmo
